export const INTERVAL_HEIGHT = 40
export const HEADER_HEIGHT = 30
export const MOUSE_MOVE_THRESHOLD = INTERVAL_HEIGHT / 4 / 4
export const MIN_BLOCK_HEIGHT = INTERVAL_HEIGHT / 4
export const RESIZE_THRESHOLD = 5
